"""add_app_perm_mode_and_description

Revision ID: 47b36871eab4
Revises: 
Create Date: 2026-06-18 11:21:30.106984
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b36871eab4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_apps', sa.Column('perm_mode', sa.String(length=16), server_default='full', nullable=False, comment='权限管理模式: full=完整RBAC | role_only=仅角色'))
    op.add_column('auth_apps', sa.Column('description', sa.String(length=255), nullable=True, comment='系统描述'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_apps', 'description')
    op.drop_column('auth_apps', 'perm_mode')
    # ### end Alembic commands ###
